spin_manifest_version = 2

[application]
authors = ["Michael Maymann <112947113+mmaymann@users.noreply.github.com>"]
description = ""
name = "typescript"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "typescript"

[component.typescript]
source = "target/typescript.wasm"
exclude_files = ["**/node_modules"]
[component.typescript.build]
command = "npm run build"
watch = ["src/**/*.js", "package.json"]
