spin_manifest_version = 2

[application]
authors = ["Michael Maymann <m@maymann.com>"]
description = ""
name = "dotnet"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "dotnet"

[component.dotnet]
source = "bin/Release/net8.0/wasi-wasm/dotnet.wasm"
allowed_outbound_hosts = ["http://localhost:3000"]
[component.dotnet.build]
command = "dotnet build -c Release"
